### ISSUE TITLE
Feature Request: Cleaner Nav Bar

### ISSUE THREAD

**Issue by nocturno709** [MiahNelah/cleaner-sheet-title-bar#9]
![cleanUI](https://user-images.githubusercontent.com/47069708/202803128-dc7800c1-8295-437b-b1d6-6ad92962c605.png)

Would it be possible to add an option to also clean up the nav bar in the same way as the title bar? as shown in the highlighted pic

**Comment by MiahNelah** [comment]
Hi @nocturno709 and thanks for your feedback ! This is a neat idea, I never thought about tweaking navbar. I'm quite busy right now but I'll definitely look into it when I'll get some free time !

**Comment by nocturno709** [comment]
Woohoo looking forward to it! 😀 I have had to disable a few mods because they get pushed off to the sides lol this would be amazing

**Comment by MiahNelah** [comment]
![image](https://user-images.githubusercontent.com/1334405/204089595-732d117e-020a-41cd-9bfe-9875b82dc141.png)
Here is a first glimpse. It's not done yet, I need to add settings and test it everywhere. I may also look to set menu vertically on side too.

**Comment by nocturno709** [comment]
Oh my goodness ! This looks fantastic. What a life saver

**Comment by nocturno709** [comment]
Also I love the vertical on the side idea. Good thinking!

**Comment by MiahNelah** [comment]
I did some tests this week-end : this evolution break a lot of thing, especially on character sheet :( I'll look for another way to handle thoses tabs.

**Comment by nocturno709** [comment]
oh no! Hope it comes easy for you!

**Comment by MiahNelah** [comment]
It looks like I find a way to handle issues. Everything look fine now. I don't have time yet to publish update, so you can try by yourself with a manual installation using this manifest link : 
https://github.com/MiahNelah/cleaner-sheet-title-bar/releases/download/v1.5.0/module.json

If you encounter some issues, you can just uninstall module then reinstall it like any modules. Please report issues here too 👍

**Comment by nocturno709** [comment]
Awesome! Works great so far!! 😀😀😀
